// Package git implements a Git smart HTTP proxy with credential injection and
// two-level disk caching for refs and pack files.
//
// Handler can be mounted directly on an HTTP server. It provides:
//
//   - Credential injection through generated gitconfig extraHeader entries
//   - Level 1 refs advertisement cache (short TTL, small)
//   - Level 2 full-clone pack cache (LRU-only, large)
//   - Singleflight request coalescing for concurrent clones
//   - Push-triggered cache invalidation
package git

import (
	"encoding/base64"
	"fmt"
	"strings"
)

// GitCredentialConfig describes how to configure Git credentials for a container.
type GitCredentialConfig struct {
	// Hosts lists the Git hosts for which credentials should be configured.
	Hosts []GitHostCredential `json:"hosts"`
}

// GitHostCredential configures credentials for one Git hosting service.
type GitHostCredential struct {
	// Host is the hostname of the Git service (e.g., "github.com", "gitlab.com").
	Host string `json:"host"`

	// EnvVar is the name of the environment variable holding the real token.
	// The container will receive this variable set to the ags-<hash> placeholder.
	EnvVar string `json:"env"`

	// Username is the Basic auth username to send. GitHub accepts any value
	// (convention: "x"), GitLab/Bitbucket may require the actual username.
	// Default: "x".
	Username string `json:"username,omitempty"`

	// SSHRewrite, if true, adds a url.insteadOf rule rewriting git@<host>:
	// to https://<host>/.
	SSHRewrite bool `json:"sshRewrite,omitempty"`
}

// GenerateStaticGitConfig generates the base gitconfig that is shared by all
// containers. Callers can write or mount the result as a system-level Git
// configuration file. The generated configuration includes proxy CA trust.
//
// caBundlePath is the in-container path to the CA bundle (e.g.,
// "/etc/ssl/certs/agentuity-ca-bundle.crt"). If empty, http.sslCAInfo is omitted.
func GenerateStaticGitConfig(caBundlePath string) string {
	var sb strings.Builder
	sb.WriteString("# Generated by proxykit.\n")
	sb.WriteString("# System Git configuration with proxy-aware settings.\n\n")

	sb.WriteString("[core]\n")
	sb.WriteString("\thooksPath = /dev/null\n")
	sb.WriteString("\tsymlinks = false\n")
	sb.WriteString("\tautocrlf = input\n\n")

	if caBundlePath != "" {
		sb.WriteString("[http]\n")
		sb.WriteString(fmt.Sprintf("\tsslCAInfo = %s\n\n", caBundlePath))
	}

	sb.WriteString("[credential]\n")
	sb.WriteString("\thelper = \"\"\n\n")

	sb.WriteString("[safe]\n")
	sb.WriteString("\tdirectory = *\n\n")

	sb.WriteString("[user]\n")
	sb.WriteString("\temail = agentuity[bot]@users.noreply.github.com\n")
	sb.WriteString("\tname = agentuity[bot]\n")

	return sb.String()
}

// GenerateGitConfig generates a per-container gitconfig with credential injection.
// This extends the static config with host-specific Authorization headers and
// optional SSH URL rewriting. Only needed when GitCredentials are provided.
//
// caBundlePath is the in-container path to the CA bundle.
// creds must be non-nil with at least one Host entry.
// env is the container's environment map, which should already contain the
// hashed ags-xxx tokens for the credential env vars (set by the proxy hook).
func GenerateGitConfig(caBundlePath string, creds *GitCredentialConfig, env map[string]string) string {
	// Start with the static base.
	sb := strings.Builder{}
	sb.WriteString(GenerateStaticGitConfig(caBundlePath))

	if creds == nil {
		return sb.String()
	}

	for _, cred := range creds.Hosts {
		host := strings.TrimSpace(cred.Host)
		if host == "" {
			continue
		}

		username := cred.Username
		if username == "" {
			username = "x"
		}

		// Get the token from the env map. The proxy hook has already hashed
		// the env vars, so the value should be an ags-xxx token.
		token := env[cred.EnvVar]
		if token == "" {
			continue
		}

		raw := username + ":" + token
		encoded := base64.StdEncoding.EncodeToString([]byte(raw))

		sb.WriteString(fmt.Sprintf("\n# ── %s ──\n\n", host))
		sb.WriteString(fmt.Sprintf("[http %q]\n", "https://"+host))
		sb.WriteString(fmt.Sprintf("\textraHeader = Authorization: Basic %s\n\n", encoded))

		if cred.SSHRewrite {
			sb.WriteString(fmt.Sprintf("[url %q]\n", "https://"+host+"/"))
			sb.WriteString(fmt.Sprintf("\tinsteadOf = git@%s:\n\n", host))
		}
	}

	return sb.String()
}
